// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKO8ElAPr4ZPneF9v-yxGHqm_2frV8OE',
    appId: '1:603914629989:web:67ad7d87674b951fdee78c',
    messagingSenderId: '603914629989',
    projectId: 'onesignal-9364f',
    authDomain: 'onesignal-9364f.firebaseapp.com',
    storageBucket: 'onesignal-9364f.firebasestorage.app',
    measurementId: 'G-XMK57QSGBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ZzVkhDZp1kMtWsstYXrVkE9ZntAibgw',
    appId: '1:603914629989:android:19a9757e4b932488dee78c',
    messagingSenderId: '603914629989',
    projectId: 'onesignal-9364f',
    storageBucket: 'onesignal-9364f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRdM2myAHMRkavnUKFsCgYuN3YPFteh4',
    appId: '1:603914629989:ios:b177da49459708e1dee78c',
    messagingSenderId: '603914629989',
    projectId: 'onesignal-9364f',
    storageBucket: 'onesignal-9364f.firebasestorage.app',
    iosBundleId: 'com.example.oneSignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRdM2myAHMRkavnUKFsCgYuN3YPFteh4',
    appId: '1:603914629989:ios:b177da49459708e1dee78c',
    messagingSenderId: '603914629989',
    projectId: 'onesignal-9364f',
    storageBucket: 'onesignal-9364f.firebasestorage.app',
    iosBundleId: 'com.example.oneSignal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKO8ElAPr4ZPneF9v-yxGHqm_2frV8OE',
    appId: '1:603914629989:web:dbb4ad3fd33de796dee78c',
    messagingSenderId: '603914629989',
    projectId: 'onesignal-9364f',
    authDomain: 'onesignal-9364f.firebaseapp.com',
    storageBucket: 'onesignal-9364f.firebasestorage.app',
    measurementId: 'G-KRNG0GRG2E',
  );
}
